export { default as About } from './About/About';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer';
export { default as Header } from './Header/Header';
export { default as Services } from './Services/Services';
export { default as Skills } from './Skills/Skills';
export { default as Home } from './Home/Home';
export { default as Work } from './Work/Work';
export { default as Projects } from './Projects/Projects';
